# example_9_6_1.yaml
image_processing:
  - platform: facebox
    scan_interval: 1000000
    ip_address: 192.168.31.214
    port: 9999
    confidence: 10
    source:
      - entity_id: camera.cam_input
        name: facebox_identify

script:
  ms_face_identify_script:
    alias: facebox人脸识别
    sequence:
      - service: image_processing.scan
        data:
          entity_id: image_processing.facebox_identify

automation:
  - alias: Clinton Identify
    trigger:
      platform: event
      event_type: image_processing.detect_face
      event_data:
        entity_id: image_processing.facebox_identify
        name: 'Clinton'
    action:
      service: persistent_notification.create
      data_template:
        title: 'facebox人脸认证'
        message: '克林顿出现在摄像头中，可信度{{ trigger.event.data.confidence }}%'
